name: Zip and Publish CLI Code

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  zip-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Zip CLI Code
        run: |
          cd cli_code
          zip -r ../bgh-cli.zip .

      - name: Upload CLI code to current release
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: bgh-cli.zip
          asset_name: bgh-cli.zip
          asset_content_type: application/octet-stream